"""Add Freebie model

Revision ID: 6d6dda6ca708
Revises: c284f03d2419
Create Date: 2024-09-16 12:45:03.722078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6dda6ca708'
down_revision = 'c284f03d2419'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
