"""Add freebies table

Revision ID: c156bcdb679f
Revises: e7129d32208d
Create Date: 2024-09-16 12:52:23.600488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c156bcdb679f'
down_revision = 'e7129d32208d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_dev_id_devs', type_='foreignkey')
        batch_op.drop_column('dev_id')

    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_devs_company_id_companies', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_devs_company_id_companies', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_companies_dev_id_devs', 'devs', ['dev_id'], ['id'])

    # ### end Alembic commands ###
