"""Add Freebie model

Revision ID: c284f03d2419
Revises: d1276bb86e72
Create Date: 2024-09-16 12:44:01.344562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c284f03d2419'
down_revision = 'd1276bb86e72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
