"""Add Freebie model

Revision ID: d1276bb86e72
Revises: fdd0a9f8ff20
Create Date: 2024-09-16 12:42:08.952826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1276bb86e72'
down_revision = 'fdd0a9f8ff20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
