"""Add Freebie model

Revision ID: e7129d32208d
Revises: 6d6dda6ca708
Create Date: 2024-09-16 12:46:43.551156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7129d32208d'
down_revision = '6d6dda6ca708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
