"""Add Freebie model

Revision ID: fdd0a9f8ff20
Revises: 2fd3d078e220
Create Date: 2024-09-16 12:41:25.964296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd0a9f8ff20'
down_revision = '2fd3d078e220'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_companies_dev_id_devs'), 'devs', ['dev_id'], ['id'])

    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_devs_company_id_companies'), 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_devs_company_id_companies'), type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_companies_dev_id_devs'), type_='foreignkey')
        batch_op.drop_column('dev_id')

    # ### end Alembic commands ###
